version: "3.7"

services:
  frontend:
    container_name: fck_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
  backend:
    container_name: fck_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    # dns:
    #   - 8.8.8.8
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
