from app.models.user import User
from app.resources.update_user_dto import UpdateUserDTO
from app.resources.user_dto import UserDTO
from typing import List


class UserService:
    def activate_user_by_id(self, user_id: str) -> UserDTO: ...
    def deactivate_user_by_id(self, user_id: str) -> UserDTO: ...
    def get_auth_id_by_user_id(self, user_id: str) -> str: ...
    def get_user_by_auth_id(self, auth_id: str) -> User: ...
    def get_user_by_id(self, user_id: str) -> UserDTO: ...
    def get_user_role_by_auth_id(self, auth_id: str) -> str: ...
    def get_users(self) -> List[UserDTO]: ...
    def update_user_by_id(
        self,
        user_id: str,
        update_user_dto: UpdateUserDTO
    ) -> UserDTO: ...
    def update_user_coordinates(
        self,
        user_dto: UpdateUserDTO
    ) -> UpdateUserDTO: ...
