from graphene.types.context import Context
from typing import (
    Dict,
    Union,
)
from unittest.mock import Mock
from werkzeug.datastructures import MultiDict


class Cookies:
    def __delattr__(self, key: str) -> None: ...
    def __getattr__(self, key: str) -> int: ...
    def __init__(self, context: Context) -> None: ...
    def __setattr__(self, key: str, value: Union[int, MultiDict, Dict[str, int]]) -> None: ...
    def add_to_response(self, response: Mock) -> Mock: ...
