from _typeshed import Incomplete

def get_version(version: Incomplete | None = None): ...
def get_main_version(version: Incomplete | None = None): ...
def get_complete_version(version: Incomplete | None = None): ...
def get_docs_version(version: Incomplete | None = None): ...
def get_git_changeset(): ...
