from _typeshed import Incomplete

__all__ = ['BaseField', 'ComplexBaseField', 'ObjectIdField', 'GeoJsonBaseField']

class BaseField:
    name: Incomplete
    creation_counter: int
    auto_creation_counter: int
    db_field: Incomplete
    required: Incomplete
    default: Incomplete
    unique: Incomplete
    unique_with: Incomplete
    primary_key: Incomplete
    validation: Incomplete
    choices: Incomplete
    null: Incomplete
    sparse: Incomplete
    def __init__(self, db_field: Incomplete | None = None, required: bool = False, default: Incomplete | None = None, unique: bool = False, unique_with: Incomplete | None = None, primary_key: bool = False, validation: Incomplete | None = None, choices: Incomplete | None = None, null: bool = False, sparse: bool = False, **kwargs) -> None: ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value) -> None: ...
    def error(self, message: str = '', errors: Incomplete | None = None, field_name: Incomplete | None = None) -> None: ...
    def to_python(self, value): ...
    def to_mongo(self, value): ...
    def prepare_query_value(self, op, value): ...
    def validate(self, value, clean: bool = True) -> None: ...
    @property
    def owner_document(self): ...
    @owner_document.setter
    def owner_document(self, owner_document) -> None: ...

class ComplexBaseField(BaseField):
    field: Incomplete
    def __init__(self, field: Incomplete | None = None, **kwargs) -> None: ...
    def __set__(self, instance, value): ...
    def __get__(self, instance, owner): ...
    def to_python(self, value): ...
    def to_mongo(self, value, use_db_field: bool = True, fields: Incomplete | None = None): ...
    def validate(self, value) -> None: ...
    def prepare_query_value(self, op, value): ...
    def lookup_member(self, member_name): ...

class ObjectIdField(BaseField):
    def to_python(self, value): ...
    def to_mongo(self, value): ...
    def prepare_query_value(self, op, value): ...
    def validate(self, value) -> None: ...

class GeoJsonBaseField(BaseField):
    def __init__(self, auto_index: bool = True, *args, **kwargs) -> None: ...
    def validate(self, value): ...
    def to_mongo(self, value): ...
