__all__ = ['DocumentMetaclass', 'TopLevelDocumentMetaclass']

class DocumentMetaclass(type):
    def __new__(mcs, name, bases, attrs): ...

class TopLevelDocumentMetaclass(DocumentMetaclass):
    def __new__(mcs, name, bases, attrs): ...
    @classmethod
    def get_auto_id_names(mcs, new_class): ...

class MetaDict(dict):
    def merge(self, new_options) -> None: ...

class BasesTuple(tuple): ...
