class LazyRegexCompiler:
    def __init__(self, pattern, flags: int = 0) -> None: ...
    @property
    def compiled_regex(self): ...
    def __get__(self, instance, owner): ...
    def __set__(self, instance, value) -> None: ...
