from _typeshed import Incomplete

class OrderedType:
    creation_counter: int
    def __init__(self, _creation_counter: Incomplete | None = None) -> None: ...
    @staticmethod
    def gen_counter(): ...
    def reset_counter(self) -> None: ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __gt__(self, other): ...
    def __hash__(self): ...
