from .scalars import Scalar as Scalar
from _typeshed import Incomplete

class Date(Scalar):
    @staticmethod
    def serialize(date): ...
    @classmethod
    def parse_literal(cls, node, _variables: Incomplete | None = None): ...
    @staticmethod
    def parse_value(value): ...

class DateTime(Scalar):
    @staticmethod
    def serialize(dt): ...
    @classmethod
    def parse_literal(cls, node, _variables: Incomplete | None = None): ...
    @staticmethod
    def parse_value(value): ...

class Time(Scalar):
    @staticmethod
    def serialize(time): ...
    @classmethod
    def parse_literal(cls, node, _variables: Incomplete | None = None): ...
    @classmethod
    def parse_value(cls, value): ...
