from _typeshed import Incomplete
from graphql import (
    GraphQLEnumType,
    GraphQLInputObjectType,
    GraphQLInterfaceType,
    GraphQLObjectType,
    GraphQLScalarType,
    GraphQLUnionType,
)

class GrapheneGraphQLType:
    graphene_type: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...

class GrapheneInterfaceType(GrapheneGraphQLType, GraphQLInterfaceType): ...
class GrapheneUnionType(GrapheneGraphQLType, GraphQLUnionType): ...
class GrapheneObjectType(GrapheneGraphQLType, GraphQLObjectType): ...
class GrapheneScalarType(GrapheneGraphQLType, GraphQLScalarType): ...

class GrapheneEnumType(GrapheneGraphQLType, GraphQLEnumType):
    def serialize(self, value): ...

class GrapheneInputObjectType(GrapheneGraphQLType, GraphQLInputObjectType): ...
