from .unmountedtype import UnmountedType as UnmountedType
from .utils import get_type as get_type

class Structure(UnmountedType):
    def __init__(self, of_type, *args, **kwargs) -> None: ...
    @property
    def of_type(self): ...
    def get_type(self): ...

class List(Structure):
    def __eq__(self, other): ...

class NonNull(Structure):
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
