from ..utils.orderedtype import OrderedType as OrderedType
from _typeshed import Incomplete

class UnmountedType(OrderedType):
    args: Incomplete
    kwargs: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def get_type(self) -> None: ...
    def mount_as(self, _as): ...
    def Field(self): ...
    def InputField(self): ...
    def Argument(self): ...
    def __eq__(self, other): ...
