name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"

      - name: Set up Node.js
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"
          cache: "yarn"
          cache-dependency-path: frontend/yarn.lock

      - name: Install Node.js dependencies
        if: steps.changes.outputs.frontend == 'true'
        run: yarn --cwd ./frontend --prefer-offline

      - name: Lint frontend
        if: steps.changes.outputs.frontend == 'true'
        working-directory: ./frontend
        run: yarn lint

      - name: Lint backend
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: pip install black flake8 && python -m black --check . --exclude "".*typings.*|test_csv.py"
