name: "Prod: Deploy frontend"

# We have disabled automatic dispatch, since we want to deploy prod manually
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
#     paths:
#       - "frontend/**"

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/firebase-deploy
        with:
          channelId: live
          backendUrl: "${{ vars.BACKEND_URL }}"
          oauthClientId: "${{ vars.OAUTH_CLIENT_ID }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SVC_ACCOUNT_JSON }}"
          projectId: "${{ vars.FIREBASE_PROJECT_ID }}"
