name: "Staging: Deploy frontend"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/firebase-deploy
        with:
          channelId: live
          backendUrl: "${{ secrets.BACKEND_URL_STAGING }}"
          oauthClientId: "${{ secrets.OAUTH_CLIENT_ID_STAGING }}"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SVC_ACCOUNT_JSON_STAGING }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID_STAGING }}"
